# Generated by Django 4.2.7 on 2023-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderPayment',
            field=models.TextField(choices=[('КП', 'Картой при получении'), ('НП', 'Наличными при получении')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.TextField(choices=[('ОФ', 'Оформлен'), ('СЗ', 'Сбор заказа'), ('ДС', 'Доставка курьером'), ('ДО', 'Доставлен')], default=('ОФ', 'Оформлен')),
        ),
    ]
