# Generated by Django 4.2.7 on 2023-12-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_orderpayment_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderCost',
            field=models.TextField(),
        ),
    ]
