# Generated by Django 4.2.7 on 2023-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_ordercost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderAddress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderPhoneNumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.TextField(choices=[('ОФ', 'Оформлен'), ('СЗ', 'Сбор заказа'), ('ДС', 'Доставка курьером'), ('ДО', 'Доставлен')], default='Оформлен'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
