# Generated by Django 4.2.7 on 2023-12-14 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_options_alter_request_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_alter_order_orderaddress_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['orderDate'], 'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Продукты в заказах', 'verbose_name_plural': 'Продукты в заказах'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='orderAddress',
            field=models.CharField(max_length=50, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderCost',
            field=models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderEmployee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderPayment',
            field=models.TextField(choices=[('КП', 'Картой при получении'), ('НП', 'Наличными при получении')], verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderPhoneNumber',
            field=models.CharField(max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.TextField(choices=[('ОФ', 'Оформлен'), ('СЗ', 'Сбор заказа'), ('ДС', 'Доставка курьером'), ('ДО', 'Доставлен')], default='Оформлен', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='OrderId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='ProductAmount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='ProductId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCost',
            field=models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImg',
            field=models.FileField(upload_to='static/img/prodImg', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.TextField(max_length=50, verbose_name='Нименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.TextField(choices=[('Овощи', 'Овощи'), ('Фрукты', 'Фрукты'), ('Готовая продукция', 'Готовая продукция'), ('Прочее', 'Прочее')], verbose_name='Тип продукта'),
        ),
    ]
