# Generated by Django 4.2.7 on 2023-12-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.TextField(choices=[('В наличии', 'В наличии'), ('Не в начличии', 'Не в начличии')], default='В наличии', verbose_name='Статус'),
        ),
    ]
