# Generated by Django 5.0.6 on 2024-05-30 12:27

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_orderphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderPhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU'),
        ),
    ]
