# Generated by Django 5.0.6 on 2024-05-31 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_orderphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderPhoneNumber',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Неверный формат номера телефона', regex='^\\+?7?\\d{9,10}$')]),
        ),
    ]
