# Generated by Django 5.0.6 on 2024-06-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_order_orderdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['orderDate'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Продукт в заказе', 'verbose_name_plural': 'Продукты в заказе'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderEmployee',
        ),
    ]
